### ISSUE TITLE
Program stops working

### ISSUE THREAD

**Issue by chibifibi** [SachsenCoder/Anita#14]
Hi again SachsenCoder.

It looks like the software stops working after it begins fetching data. I am able to find a person but the program halts after a few seconds after clicking on Fetch Data.

**Comment by SachsenCoder** [comment]
I will check this, when I'm in the mood and find some time. :-)

**Comment by chibifibi** [comment]
Hi sir. Have you had a chance to work on this? :)

**Comment by ChristianG1984** [comment]
OK, the new version is ready. Check out the release section! :-)

**Comment by chibifibi** [comment]
Works like a charm so far! Thank you so much! :)
