### ISSUE TITLE
Anita Crash on Windows 8

### ISSUE THREAD

**Issue by chonini** [SachsenCoder/Anita#15]
The program crash when I tried to fetch data.

**Comment by thehelpguy** [comment]
Same on Windows 7.

**Comment by hirenshah** [comment]
Yep, worked a few months ago nut now just crashes when I press Fetch on Windows 10.

**Comment by ChristianG1984** [comment]
I will check this out, when I have time for it. I'm sure, they changed something on their website that is incompatible with my tool now.

**Comment by ChristianG1984** [comment]
Hmmm, I wonder, why it crashes. When I hit "Fetch Data", it works without a crash. (Try to fetch "Jessica Alba (I)" for example.)
Could you guys give me some example search queries, so that I can try to reproduce the crash? That would be very helpful.

**Comment by thehelpguy** [comment]
I downloaded the Anita again and I have no idea why but it works fine.

**Comment by thehelpguy** [comment]
My guess it's a hard disk (read/write) issue, like bad blocks  Anita cannot handle and them crash. but essentially program works normal.

**Comment by ChristianG1984** [comment]
A new Release is available. Maybe, it fixes this Issue.
