### ISSUE TITLE
Anita has been crashing on Windows 10. Love your work. Can you please take a look?

### ISSUE THREAD

**Issue by Kouvan** [SachsenCoder/Anita#18]
Hi Sachsen. Thank you very much for the new release. I still experience the error mentioned by Thymopat: "After clicking on "Fetch Data" it will crash on Windows 10".

**Comment by ghost** [comment]
After clicking on "Fetch Data" it will crash on Windows 10

**Comment by ChristianG1984** [comment]
I think, I also got this error yesterday. I debugged and fixed this bug locally on my computer successfully. I try to publish this new release today, when I'm at home.

**Comment by ChristianG1984** [comment]
A new Release is available. Maybe, it fixes this Issue.

**Comment by hirenshah** [comment]
Still not fixed :(
