### ISSUE TITLE
R1.8

### ISSUE THREAD

**Issue by Kouvan** [SachsenCoder/Anita#19]
Hi Christian. Thank you very much for the new release. I still experience the error mentioned by Thymopat: "After clicking on "Fetch Data" it will crash on Windows 10".

**Comment by hirenshah** [comment]
Yep, same issue here... cannot seem to make it work on Windows 10 :(

**Comment by ChristianG1984** [comment]
Ok, I figured out the problem and it is fixed now. :-)
(By the way: The wikifeet website becomes more and more ugly, because of the crappy and aggressive ads around.)

**Comment by hirenshah** [comment]
Confirmed.  Works fine now.  Thanks :)
