### ISSUE TITLE
cant search for any celebrities 

### ISSUE THREAD

**Issue by 98115** [SachsenCoder/Anita#21]
whenever i type in a celebs name nothing pops up so i cant click on the celebs name and click fetch data.  there is no error message of any kind.

**Comment by ChristianG1984** [comment]
Sorry for the late response! (I have not recognized the notification about that Issue in my mail box.) 
Some days ago, I got the same problem when I tried to use the tool. I solved the problem. I will upload the fixed version when I'm at home.

**Comment by innerhorror** [comment]
Thanks, just saw this issue also.
