### ISSUE TITLE
Having issues

### ISSUE THREAD

**Issue by Kouvan** [SachsenCoder/Anita#23]
Hi,
Stops working after fetch data. Can you please look into it?
Thank you very much
Kourosh

**Comment by Odd67** [comment]
Same problem for me.
When I click "fetch data" it stops working and closes immediately.

**Comment by Leryn** [comment]
same

**Comment by Odd67** [comment]
wikifeet changed the code source of their site

does anyone know the mail of the creator of the script ?

**Comment by Leryn** [comment]
try here

kreshnov@gmail.com

**Comment by Leryn** [comment]
is the email of creator of the site

**Comment by ChristianG1984** [comment]
Hello guys! Yeah, they changed their site.
I'm currently planning ... well, working on ... a better version, based on the [electron framework](https://electronjs.org/), especially [electron-forge](https://electronforge.io/). I hope, that I can release a bare working version soon. (Even, if it should look ugly at first, but that you can download the pictures. I would like to take more time later on to polish things up and make it nice.) So, stay tuned! :-)

**Comment by Leryn** [comment]
thank you ;)
